version: '3'
services:
    php:
      container_name: php
      build:
        context: .
        dockerfile: php/Dockerfile
      networks:
        - myapp_net
      env_file:
         - variable.env
    nginx-front:
      container_name: nginx-front
      env_file:
         - variable.env
      build:
        context: .
        dockerfile: nginx/Dockerfile
      ports: 
        - "8080:80"
      networks:
        - myapp_net
      depends_on:
        - php
networks:
   myapp_net: 
